#!/usr/bin/env python3
"""Insert deck-house-rules pointers into every installed ppt-master copy (idempotent).

Run after `claude plugin update ppt-master@ppt-master`. Exit code != 0 when a copy
is missing an anchor or its attribution guard fails after patching.
"""

import subprocess
import sys
from pathlib import Path

RULES = str(Path(__file__).resolve().parents[1] / "SKILL.md").replace(str(Path.home()), "~", 1)
MARK = "deck-house-rules"
POINTERS = {
    # file: (anchor line prefix, pointer text); pointer goes right after the anchor line
    "SKILL.md": (
        "# ",
        f"> **Local house rules ({MARK}):** before planning images or decoration read `{RULES}` — slide images only via claudex-loop + Codex `$imagegen`; no glow-ellipse highlights.",
    ),
    "references/image-generator.md": (
        "**Trigger**",
        f"> **Local house rule ({MARK}):** in this environment AI images are planned by the host and generated by Codex `$imagegen` through claudex-loop — follow §1 of `{RULES}`.",
    ),
    "references/executor-base.md": (
        "# ",
        f"> **Local house rule ({MARK}):** never highlight numbers, labels or titles with glow ellipses / radial halos; use a native accent-outlined shape without fill instead — §2 of `{RULES}`.",
    ),
}


def patch(root: Path) -> bool:
    ok = True
    for rel, (anchor, pointer) in POINTERS.items():
        path = root / rel
        lines = path.read_text(encoding="utf-8").split("\n")
        if any(MARK in line for line in lines):
            continue
        body_start = (
            lines.index("---", 1) + 1 if rel == "SKILL.md" else 0
        )  # skip frontmatter
        hit = next(
            (i for i in range(body_start, len(lines)) if lines[i].startswith(anchor)),
            None,
        )
        if hit is None:
            print(f"[FAIL] anchor {anchor!r} not found in {path}")
            ok = False
            continue
        lines[hit + 1 : hit + 1] = ["", pointer]
        path.write_text("\n".join(lines), encoding="utf-8")
        print(f"[OK] patched {path}")
    guard = subprocess.run(
        [sys.executable, str(root / "scripts/attribution_guard.py")],
        capture_output=True,
        text=True,
    )
    print(f"[{'OK' if guard.returncode == 0 else 'FAIL'}] attribution_guard {root}")
    return ok and guard.returncode == 0


roots = sorted(
    Path.home().glob(".claude/plugins/cache/ppt-master/ppt-master/*/ppt-master")
)
if not roots:
    sys.exit("[FAIL] ppt-master is not installed")
sys.exit(0 if all([patch(r) for r in roots]) else 1)
